### ISSUE TITLE
GLIBC_2.34 Not Found

### ISSUE THREAD

**Issue by thefunvampire** [karlsen-network/karlsen-stratum-bridge#11]
Good morning, I tried following the guide to use the bridge on HiveOS rig, but it's giving me errors "GLIBC_2.32 and GLIBC_2.34 not found (Required by kls_bridge)."

Apparently Hive uses OS 18, I guess it doesn't come with everything needed?

Appreciate your time and assistance on this :) Thanks

**Comment by LeChatNoir69** [comment]
Yep, it works with static.

**Comment by lemois-1337** [comment]
Fixed in `v2.0.0` with 403a929f44a6c6ee5eb73abdbb77dea7fa63f46f
